### ISSUE TITLE
Support for more presets

### ISSUE THREAD

**Issue by stomko11** [vindaalex/multizone-thermostat#24]
Would it be doable to add support for more custom presets? I usually use 2 different away modes - one for short term away, one for longer. Right now I set that via scheduler, but would be nice to have direct support by thermostat.

**Comment by vindaalex** [comment]
One additional preset should be possible. I'll have a look

**Comment by stomko11** [comment]
Option to name both custom presets would be great. I believe now away is called away and cannot be changed, correct?

**Comment by vindaalex** [comment]
A brief update. I've got the additional presets working however also found out that the coordination of thermostats need some checking. Hi pe to have mid next week a release.

**Comment by vindaalex** [comment]
I've placed a new version in the branch 'refactor' which supports custom presets [link](https://github.com/vindaalex/multizone-thermostat/tree/refactor). Would you be able to test this version? I think next week I'll release it via HACS.

Please note that it has significant changes compared to the previous releases regarding operatien and some new functionality. See a worked-out example in the [examples](https://github.com/vindaalex/multizone-thermostat/tree/refactor/examples/multizone thermostat - explanation.yaml)

**Comment by vindaalex** [comment]
Closing issue. Released version v0.7 which includes this functionality.
