### ISSUE TITLE
New thermostat card 2023.12 update doesn't show preset_mode

### ISSUE THREAD

**Issue by bezigebever** [vindaalex/multizone-thermostat#25]
After upgrade of HA to 2023.12 with hte new thermostat card, the preset_mode isn't displayed, so no warning when thermostat is in emergency mode.
In the docs I can't really find a solution... Any workaround ?

**Comment by vindaalex** [comment]
I've placed a new version in the branch 'refactor' which should show the emergency mode in [link](https://github.com/vindaalex/multizone-thermostat/tree/refactor). Would you be able to test this version? I think next week I'll release it via HACS.

Please note that it has significant changes compared to the previous releases regarding operatien and some new functionality. See a worked-out example in the [examples](https://github.com/vindaalex/multizone-thermostat/tree/refactor/examples/multizone thermostat - explanation.yaml)

**Comment by vindaalex** [comment]
I found a bug in the beta and therefore removed it again. The master pwm signal did not update correctly. I'm trying an update tonight and hopefully release a new update/beta tomorrow.

**Comment by vindaalex** [comment]
Released a new version v0.7 which should work. Closing this issue. Please reopen if it gives new issues.
