### ISSUE TITLE
After update, error on away_temp

### ISSUE THREAD

**Issue by bezigebever** [vindaalex/multizone-thermostat#29]
Afer update I have following error :
```
Logger: homeassistant.config
Source: config.py:1195
First occurred: 13:15:06 (2 occurrences)
Last logged: 13:15:06

Invalid config for 'climate.multizone_thermostat' at climate.yaml, line 20: 'away_temp' is an invalid option for 'climate.multizone_thermostat', check: heat->away_temp, please check the docs at https://github.com/vindaalex/multizone_thermostat
Invalid config for 'climate.multizone_thermostat' at climate.yaml, line 59: 'away_temp' is an invalid option for 'climate.multizone_thermostat', check: heat->away_temp, please check the docs at https://github.com/vindaalex/multizone_thermostat
```
Thermostat is no longer working.

**Comment by bezigebever** [comment]
I temporarely commented out the awa_temp parameter, after restart the thermostat seems to be working.

**Comment by vindaalex** [comment]
Did you update to the beta version? Then it will fail when booting after update when away preset is defined. Updating has it's merits:
- new config options cannot be defined before updating and reboot is not possible
- removed config options will give errors after reboot.

So only after a reboot to the new version, new config options can be included. And to avoid errors while updating , removed options need to be removed from config.

With this beta version the 'away' preset has been replaced by 'extra_presets'. You can read more about it in the beta version readme and/or at the examples folder wirhin the multizone explained file.

**Comment by bezigebever** [comment]
Indeed running the beta version and I had missed the change in the config. extra_presets is working :-)
I also have another error on my template sensors:
```
Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:194
Integration: Template (documentation, issues)
First occurred: 17:46:05 (6 occurrences)
Last logged: 17:59:13

TemplateError('UndefinedError: 'None' has no attribute 'heat'') while processing template 'Template<template=({{ state_attr('climate.beneden', 'hvac_def')['heat']['PID_P'] | float(0)}}) renders=14>' for attribute '_attr_native_value' in entity 'sensor.beneden_pid_p'
TemplateError('UndefinedError: 'None' has no attribute 'heat'') while processing template 'Template<template=({{ state_attr('climate.beneden', 'hvac_def')['heat']['PID_I'] | float(0)}}) renders=14>' for attribute '_attr_native_value' in entity 'sensor.beneden_pid_i'
TemplateError('UndefinedError: 'None' has no attribute 'heat'') while processing template 'Template<template=({{ state_attr('climate.beneden', 'hvac_def')['heat']['PID_D'] | float(0)}}) renders=14>' for attribute '_attr_native_value' in entity 'sensor.beneden_pid_d'
TemplateError('UndefinedError: 'None' has no attribute 'heat'') while processing template 'Template<template=({{ state_attr('climate.beneden', 'hvac_def')['heat']['PID_valve_pos'] | float(0)}}) renders=14>' for attribute '_attr_native_value' in entity 'sensor.beneden_pid_valve_pos'
TemplateError('UndefinedError: 'None' has no attribute 'heat'') while processing template 'Template<template=({{ state_attr('climate.beneden', 'hvac_def')['heat']['control_output']['pwm_out'] | float(0)}}) renders=14>' for attribute '_attr_native_value' in entity 'sensor.beneden_pwm_out'
```
Not clear for me what goes wrong, mayube you can shed a light.
Many thanks !

**Comment by vindaalex** [comment]
The thermostat has not been initialsied yet and therefore ithe template cannot read the pid values. You could include an if statement, something like  'if climate = none, then none , else ...'

**Comment by vindaalex** [comment]
Regarding the config error I'll try to convert old configs to the new version and issue a warning.

**Comment by bezigebever** [comment]
Issue a warning would be great, as not alway reading all release notes...
Many thanks ! Can be closed.
