### ISSUE TITLE
Thermal actuators

### ISSUE THREAD

**Issue by SerialDestructor** [vindaalex/multizone-thermostat#30]
I'm considering to implement multizone-thermostat in my home. My radiator valves are controlled by thermal actuators.

Is there some way to make multizone-thermostat take into account that those need time to change their state? I my case, it takes about 2:30 for them to fully open. Enabling the boiler prematurely means it gets the hot water directly back into the return pipe (through the bypass), which could - at best - get it to enter a fault state.

**Comment by vindaalex** [comment]
This should be feasible to implement. I'll try to include in it in the next beta version. I expect probably somewhere next week.

**Comment by vindaalex** [comment]
Implemented this request in v0.7.
